# Generated by Django 4.1.7 on 2023-05-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_pizzeria_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
